<div class="home">
    <div class="welcome">
        <?php echo $_SESSION['txt'][$_SESSION['lang']]['home']['welcome'] . ' ' . $_SESSION['currentUser']['userName'] . '!!'; ?>
    </div>
    <div class="points"><?php echo 'Points: ' . $_SESSION['currentUser']['points']; ?></div>
    <div class="level"><?php echo 'Level: ' . $_SESSION['currentUser']['level']; ?></div>
    <div class="trainingButtons">
        <?php
        $questionTypes = $_SESSION['questionTypes'];
        $numQuestionTypes = count($questionTypes);
        for ($questionTypeIndex = 0; $questionTypeIndex < $numQuestionTypes; $questionTypeIndex++) {
            echo '<div class="trainingTypeButton">';
            echo '<a href="' . $this->basePath() . '/mtguru/index/game?questionType=' . $questionTypes[$questionTypeIndex][0] . '">' . $questionTypes[$questionTypeIndex][0] . '</a>';
            echo '</div>';
        }
        ?>
    </div>
    <div class="button" style="clear:both">
        <a href="<?php echo $this->basePath() ?>"><?= $_SESSION['txt'][$_SESSION['lang']]['home']['home'] ?></a>
    </div>
</div>

