<div class="home">
    <div class="welcome">
        <?php echo $this->translate('home_welcome') . ' ' . 'CURRENT USER' . '!!'; ?>
    </div>
    <div class="points"><?php echo 'Points: ' . 'CURRENT POINTS' ?></div>
    <div class="level"><?php echo 'Level: ' . 'CURRENT LEVEL'; ?></div>
    <div class="trainingButtons">
        <?php
        $questionTypes = $_SESSION['questionTypes'];
        $numQuestionTypes = count($questionTypes);
        for ($questionTypeIndex = 0; $questionTypeIndex < $numQuestionTypes; $questionTypeIndex++) {
            echo '<div class="trainingTypeButton">';
            echo '<a href="' . $this->basePath() . '/mtguru/index/game?questionType=' . $questionTypes[$questionTypeIndex][0] . '">' . $questionTypes[$questionTypeIndex][0] . '</a>';
            echo '</div>';
        }
        ?>
    </div>
    <div class="button" style="clear:both">
        <a href="<?php echo $this->basePath() ?>"><?php echo $this->translate('home_home') ?></a>
    </div>
</div>

