version: '2'
services:
  webserver:
    build: .
    container_name: ccoach_web
    restart: always
    volumes:
      - ./zf2:/zf2-app
    ports:
      - "127.0.0.1:9090:80"
    depends_on:
      - db
  db:
    image: mysql:5.5
    container_name: ccoach_db
    restart: always
    volumes:
      - ./datadir:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: someSecurePassword
  adminer:
    image: adminer
    container_name: ccoach_adminer
    restart: always
    ports:
      - 9095:8080
    depends_on:
      - db
