version: '2'
services:
  webserver:
    build: .
    container_name: ccoach_web
    restart: always
    volumes:
      - ./zf2:/zf2-app
    ports:
      - "127.0.0.1:9090:80"
    depends_on:
      - db
    networks:
      - jdonado-nw
    expose:
      - 8888
    environment:
      - MYSQL_ROOT_PASSWORD=someSecurePassword
      - VIRTUAL_HOST=ccoach.jdonado.com
      - LETSENCRYPT_EMAIL=jdonado@jdonado.com
      - LETSENCRYPT_HOST=ccoach.jdonado.com
  db:
    image: mysql:5.5
    container_name: ccoach_db
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./datadir:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: someSecurePassword
    networks:
      - jdonado-nw
 
networks:
  jdonado-nw:
    external:
      name: jdonado-nw

