<?php
if (isset($_GET['questionType'])) {
    echo '<script>var trainingQuestionType="' . $_GET['questionType'] . '";</script>';
}?>
<div class="mainGame">
    <div class="yourPoints">12345</div>
    <div class="currentScale"></div>
    <div class="currentKey"></div>
    <div class="yourLevel">Level 2</div>
    <div class="remainingTime"></div>
    <div class="feedbackDiv"></div>
    <div class="nextButton"><a href="javascript:nextQuestion()">NEXT!!</a></div>
    <div class="gameContent">
        <div class="loading"></div>
        <div class="question">
            <div class="question genericQuestion" style="display:none">
                <div class="questionText">Question text</div>
                <div class="questionElement"></div>
                <div id="answerItemsWrapper">
                    <div class="answerItems">
                        <div class="answerItem" data-item="CMaj7">CMaj7</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="button bottomRight">
        <a href="<?php echo $this->basePath() ?>">GO HOME!</a>
    </div>
</div>
<script src="<?php echo $this->basePath() ?>/js/game.js"></script>
<script>
    startGame();
</script>