<div id="helpPages" style="display:none">
    <div id="intervalsHelp">An interval is a thing that...</div>
    <div id="chordsHelp">A chord is something like this...</div>
    <div id="scalesHelp">A scale is something like this...</div>
    <div id="degreesHelp">A degree is something like this...</div>
    <div id="areasHelp">An area is something like this...</div>
    <div id="substitutionsHelp">A substitution is something like this...</div>
</div>