<div id="helpPages" style="display:none">
    <div id="intervalsHelp">
        An interval is the difference between two notes.<br><br>
        The smallest interval has a distance of a semitone.<br><br>
        The distances between notes follow this pattern:<br>
        <img src="../img/intervalDistances.png"><br>
        <div class="exampleInline">E.g.: Between C and F there's a distance of 2.5 tones.</div><br>
        <div class="exampleInline">E.g.: Between C# and E there's a distance of 1.5 tones.</div><br><br>
        An interval between two consecutive notes will be a second; between three notes, it will be a third, and so on.<br><br>
        <div class="exampleInline">E.g.: C and F form a fourth.</div><br><br>
        The following table shows all the possible intervals:<br><br>
        <img src="../img/intervalsTable.png"><br>
        The interval types are: d (diminished); m (minor); P (perfect); M (major) and A (augmented).<br><br>
        With all of the above, we can obtain the following examples:<br><br>
        <div class="exampleInline">C,G: Perfect fifth (5P)<br>
        E,F: Minor second (2m)<br>
        B,D#: Major third (3M)<br>
        D,Ab: Diminished fifth (5d)</div><br><br>
        Ready for the game?? :-)<br><br>
    </div>
    <div id="chordsHelp">
        A chord is a set of two or more notes.<br><br>
        We already know the most basic chords (those that only have two notes, which are known as "intervals"). Eureka!!<br><br>
        The next group of chords are those that have three notes (triads).<br><br>
        The notes of a triad are named like this:<br><br>
        T - Tonic<br>
        3 - Third<br>
        5 - Fifth<br><br>
        And yes, the third forms an interval of third with the tonic, and the fifth an interval of fifth (easy, huh?). The tonic gives its name to the chord.<br><br>
        <div class="extraInformation">Info: You can add more notes to get chords with four notes, five, seven... and even change the order of the notes (inverted chords), but that's too complicated, so we will forget about them for a while (your instrument and your number of fingers will limit this too! ☺).</div><br>
        The Cassette Coach™ will ask you about chords with four notes too. These will be "Seventh Chords".<br><br>
        The following table shows you how to form triads and seventh chords. (MISSING!!)<br><br>
        <!--img src="../img/intervalsTable.png"><br-->
        <div class="exampleInline">
            M 3M 5P<br>
            m 3m 5P<br>
            dim 3m 5d<br>
            m7 3m 5P 7m<br>
            7 3M 5P 7m<br>
            Maj7 3M 5P 7M<br>
            mMaj7 3m 5P 7M<br>
            dim7 3m 5d 7m<br>
        </div>
    </div>
    <div id="scalesHelp">
        A scale is an ordered set of notes.<br><br>
        We already know a scale (do we!!??). Yes!! the diatonic scale:<br><br>
        <div class="exampleInline">C, D, E, F, G, A, B</div><br>
        The Cassette Coach™, will take the first note as the tonic of the scale.<br><br>
        In order to identify more scales, we will analyze the intervals between the tonic and all of the other notes.<br><br>
        Therefore, the diatonic scale, also known as ionian, will be analyzed like this:<br><br>
        <div class="exampleInline">T, 2M, 3M, 4P, 5P, 6M, 7M</div><br>
        The following table shows all the scales that the Cassette Coach™ will use to test you: (MISSING!!)<br><br>
        <!--img src="../img/intervalsTable.png"><br-->
        <div class="exampleInline">
            ionian:     2M 3M 4P 5P 6M 7M<br>
            dorian:     2M 3m 4P 5P 6M 7m<br>
            phrygian:   2m 3m 4P 5P 6m 7m<br>
            lydian:     2M 3M 4A 5P 6M 7M<br>
            myxolidian: 2M 3M 4P 5P 6M 7m<br>
            aeolian:    2M 3m 4P 5P 6m 7m<br>
            locrian:    2m 3m 4P 5d 6m 7m<br>
        </div><br><br>
    </div>
    <div id="degreesHelp">A degree is something like this...</div>
    <div id="areasHelp">An area is something like this...</div>
    <div id="substitutionsHelp">A substitution is something like this...</div>
</div>