<!--p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sZF2 Skeleton Application%s. You are currently running Zend Framework version %s. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p-->
<div class="home">
    <div class="welcome">
        <?php echo $_SESSION['txt'][$_SESSION['lang']]['home']['welcome'] . ' ' . $_SESSION['currentUser']['userName'] . '!!'; ?>
    </div>
    <div class="points"><?php echo 'Points: ' . $_SESSION['currentUser']['points']; ?></div>
    <div class="level"><?php echo 'Level: ' . $_SESSION['currentUser']['level']; ?></div>
    <div class="button">
        <a href="<?php echo $this->basePath() ?>/mtguru/index/game"><?= $_SESSION['txt'][$_SESSION['lang']]['home']['play'] ?></a>
    </div>
    <div class="button">
        <a href="<?php echo $this->basePath() ?>/mtguru/index/training"><?= $_SESSION['txt'][$_SESSION['lang']]['home']['training'] ?></a>
    </div>
</div>

