<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <script src="<?php echo $this->basePath() ?>/js/jquery.fittext.js"></script>
        <script src="<?php echo $this->basePath() ?>/js/jquery-1.11.1.min.js"></script>
        <link rel="stylesheet" type="text/css" media='screen and (max-width: 600px), screen and (orientation: portrait)' href="<?php echo $this->basePath() ?>/css/general.portrait.css"/>
        <link rel="stylesheet" type="text/css" media='screen and (min-width: 601px) and (orientation: landscape), screen and (min-width: 2001px)' href="<?php echo $this->basePath() ?>/css/general.landscape.css"/>
        <link rel="stylesheet" type="text/css" media='screen and (min-width: 1281px) and (max-width: 2000px) and (orientation: landscape)' href="<?php echo $this->basePath() ?>/css/bigscreen.landscape.css"/>
        <!--link rel="stylesheet" type="text/css" media='screen and (min-width: 2001px) and (orientation: landscape)' href="<?php echo $this->basePath() ?>/css/ultrabigscreen.landscape.css"/-->
        <script type="text/javascript">
            var baseUrl = '<?php echo $this->basePath() ?>';
        </script>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('MT Guru'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

<!--        <!-- Le styles -->
        <?php /*echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') */?>

        <!-- Scripts -->
        <?php /*echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; */?>

    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
    <script src="<?php echo $this->basePath() ?>/js/general.js"></script>
    <script src="<?php echo $this->basePath() ?>/js/jquery.flip.min.js"></script>
</html>
