<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <script src="<?php echo $this->basePath() ?>/js/jquery-1.11.1.min.js"></script>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() ?>/css/general.css">
        <script type="text/javascript">
            //var baseUrl = '<?php echo 'http://localhost:8080/s4l/zf2/public/mtguru'; ?>';
            var baseUrl = '<?php echo $this->basePath() ?>';
        </script>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('MT Guru'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

<!--        <!-- Le styles -->
        <?php /*echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') */?>

        <!-- Scripts -->
        <?php /*echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; */?>

    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
