<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <script src="<?php echo $this->basePath() ?>/js/jquery.fittext.js"></script>
        <script src="<?php echo $this->basePath() ?>/js/jquery-1.11.1.min.js"></script>
        <!--link rel="stylesheet" type="text/css" media='screen and (min-width: 601px) and (orientation: landscape), screen and (min-width: 2001px)' href="<?php echo $this->basePath() ?>/css/general.landscape.css"/-->
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() ?>/js/noteTester/noteTester.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() ?>/js/intervalSelector/intervalSelector.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() ?>/css/general.css"/>
        <link rel="stylesheet" type="text/css" media='screen and (min-width: 1381px) and (max-width: 2000px) and (orientation: landscape)' href="<?php echo $this->basePath() ?>/css/bigscreen.landscape.css"/>
        <link rel="stylesheet" type="text/css" media='screen and (max-width: 600px), screen and (orientation: portrait)' href="<?php echo $this->basePath() ?>/css/general.portrait.css"/>
        <script type="text/javascript">
            var baseUrl = '<?php echo $this->basePath() ?>';
        </script>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Cassette Coach'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
    <script src="<?php echo $this->basePath() ?>/js/general.js"></script>
    <script src="<?php echo $this->basePath() ?>/js/jquery.flip.min.js"></script>
</html>
