<div class="mainWrapper">
    <div class="mainDiv sevenSegText">
        <div onclick="showConfigScreen()" id="configTool"></div>
        <div onclick="logoutMe()" id="logoutTool"></div>
        <div id="toaster" style="display:none"></div>
        <div id="configScreen" style="display:none">
            <div class="closeWindow" onclick="hideConfigScreen()"></div>
            <div class="configHeader">Account Configuration</div>
            <div class="inputFields">
                <div class="inputGroup">
                    <div class="inputLabel">Full Name</div>
                    <input type="text" value="<?php echo $ident ?>" name="fullName" id="fullNameInput">
                </div>
                <div class="inputGroup">
                    <div class="inputLabel">E-Mail</div>
                    <input type="email" value="<?php echo $userid ?>" name="email" id="emailInput">
                </div>
                <div class="inputGroup">
                    <div class="inputLabel">Password</div>
                    <input type="password" name="password" id="passwordInput">
                </div>
                <div class="inputGroup">
                    <div class="inputLabel">Confirm Password</div>
                    <input type="password" name="confirmPassword" id="confirmPasswordInput">
                </div>
                <div class="afterChange">After changing your user information, you will have to log in again.</div>
            </div>
            <div class="sendButton" onclick="updateMyInfo()">Save</div>
        </div>
        <div id="homeContainer" class="homeContainer">
            <div class="front">
                <div class="home">
                    <div class="welcome fitText">
                        <?php echo $ident; ?>
                    </div>
                    <div class="points fitText"><?php echo $this->translate('points') . $numPoints; ?></div>
                    <div class="level fitText"><?php echo $this->translate('level') . $currentLevel; ?></div>
                    <div onclick="goPlay()" class="homePlay"></div><?php /*echo $this->translate('home_play') */ ?>
                    <div class="loadingTraining"></div>
                    <div onclick="showTraining()"
                         class="homeTraining"><?php /*echo $this->translate('home_training'); */ ?></div>
                </div>
            </div>
            <div class="back">
                <div style="display:none;" class="trainingView">
                    <?php
                    //$questionTypes = $_SESSION['questionTypes'];
                    $numQuestionTypes = count($questionTypes);
                    for ($questionTypeIndex = 0; $questionTypeIndex < $numQuestionTypes; $questionTypeIndex++) {
                        echo '<div class="trainingTypeButton fitText">';
                        echo '<a href="javascript:goTrain(\'' . $questionTypes[$questionTypeIndex]->getQuestionIdent() . '\');' . '">' . $this->translate($questionTypes[$questionTypeIndex]->getQuestionIdent()) . '</a>';
                        echo '</div>';
                    }
                    ?>
                    <a href="javascript:showHome()">
                        <div class="showHome"></div>
                    </a>
                </div>
            </div>
        </div>
        <div class="sideBar">
            <div id="navText"></div>
            <div id="topUsers">
                <div class="allTimes">
                    <div class="topUsersTitle fitText">All Time High Scores</div>
                    <!-- There should always be at least four users in the database -->
                    <div
                        class="firstOne fitText"><?php echo $topUsers[0]->getFullName() . ' - ' . $topUsers[0]->getPoints(); ?></div>
                    <div
                        class="secondOne fitText"><?php echo $topUsers[1]->getFullName() . ' - ' . $topUsers[1]->getPoints(); ?></div>
                    <div
                        class="thirdOne fitText"><?php echo $topUsers[2]->getFullName() . ' - ' . $topUsers[2]->getPoints(); ?></div>
                    <div
                        class="fourthOne fitText"><?php echo $topUsers[3]->getFullName() . ' - ' . $topUsers[3]->getPoints(); ?></div>
                </div>
                <div class="thisWeek" style="display:none">
                    <div class="topUsersTitle fitText">High Scores: this week</div>
                    <div
                        class="firstOne fitText"><?php echo $topUsersThisWeek[0]->getFullName() . ' - ' . $topUsersThisWeek[0]->getPointsThisWeek(); ?></div>
                    <div
                        class="secondOne fitText"><?php echo $topUsersThisWeek[1]->getFullName() . ' - ' . $topUsersThisWeek[1]->getPointsThisWeek(); ?></div>
                    <div
                        class="thirdOne fitText"><?php echo $topUsersThisWeek[2]->getFullName() . ' - ' . $topUsersThisWeek[2]->getPointsThisWeek(); ?></div>
                    <div
                        class="fourthOne fitText"><?php echo $topUsersThisWeek[3]->getFullName() . ' - ' . $topUsersThisWeek[3]->getPointsThisWeek(); ?></div>
                </div>
            </div>
            <div onclick="logoutMe()" class="homeLogout"><?php /*echo $this->translate('logout')*/ ?></div>
        </div>
    </div>
</div>
<div class="loadingMain" style="display:none;"></div>