<div class="loadingMain" style="display:none;"></div>
<div class="radioPageWrapper">
    <div class="radioHomeContents">
        <div class="sectionSelectors">
            <div id="selectorNeedle"></div>
            <div id="channels"></div>
            <div id="selectionFrame"></div>
            <div onclick="openCV()" class="openCV"></div>
            <div onclick="backToCassetteCoach()" class="backToCassetteCoach"></div>
            <div onclick="showMyStory()" class="sectionSelector life active"></div>
            <div onclick="showMyExperience()" class="sectionSelector experience"></div>
            <div onclick="showMyHobbies()" class="sectionSelector hobbies"></div>
        </div>
        <div class="radioHomeContent mainScreen">
            <div style="display:none" class="homePageFeedback">FeedbackText</div>
            <div class="aboutMeContentContainer">
                <div class="jDonadoSection">
                    <div style="display: none" class="section experienceSection">
                        <div class="chart uniChart">
                            <div class="chartTitle">What I studied at the Uni</div>
                            <canvas id="uniChart" width="400" height="400"></canvas>
                            <div class="legend" id="uniChartLegend"></div>
                        </div>
                        <div class="chart workChart">
                            <div class="chartTitle">What I did after that</div>
                            <canvas id="workChart" width="400" height="400"></canvas>
                            <div class="legend" id="workChartLegend"></div>
                        </div>
                        <div style="clear:both" class="chart sectorChart">
                            <div class="chartTitle">In the following sectors</div>
                            <canvas id="sectorChart" width="400" height="400"></canvas>
                            <div class="legend" id="sectorChartLegend"></div>
                        </div>
                        <div class="chart langsChart">
                            <div class="chartTitle">Mostly using this stuff</div>
                            <div id="keyWordsContainer"><div id="keyWords"></div></div>
                        </div>
                    </div>
                    <div class="section lifeSection">
                        <img class="storyOfMyLife" src="<?php echo $this->basePath() ?>/img/storyOfMyLife.svg">
                    </div>
                    <div style="display: none" class="section hobbiesSection">
                        <div class="hobbiesTitle" id="fractalFieldsTitle">You can find some of my music published under the name of "Fractal Fields"</div>
                        <a href="http://fractalfields.bandcamp.com" id="fractalFieldsIcon"></a>
                        <a href="https://play.spotify.com/album/6IxQahdMUyG5loI0FrPIwN?play=true&utm_source=open.spotify.com&utm_medium=open" id="spotifyIcon"></a>
                        <a href="http://www.amazon.com/gp/product/B00527QASW/ref=dm_ws_sp_ps_dp" id="amazonIcon"></a>
                        <a href="https://itunes.apple.com/us/album/childhood-memories/id427783028" id="itunesIcon"></a>
                        <a href="http://fractalfields.bandcamp.com" id="bandcampIcon"></a>
                        <div class="hobbiesTitle" id="picturesTitle">Whenever I can, I also enjoy taking pictures around the world :)</div>
                        <a href="https://www.flickr.com/photos/79693661@N05/" id="picturesIcon"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo $this->basePath() ?>/js/chartjs/Chart.js"></script>
<script src="<?php echo $this->basePath() ?>/js/jdonado.js"></script>
<script src="<?php echo $this->basePath() ?>/js/jqcloud/jqcloud.min.js"></script>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/js/jqcloud/jqcloud.min.css">